:title: Attributes Added by Attribute Injection
:type: dataManagement
:status: published
:parent: Automatically Added Metacard Attributes
:summary: How attribute injection adds attributes to metacards.
:order: 02

= Attributes Added by Attribute Injection

xref:managing:datamanagement/injecting-attributes.adoc[Attribute Injection] is the act of adding attributes to a metacard's xref:developing:devcomponents/metacard-type.adoc[Metacard Type].
A Metacard Type indicates the attributes available for a particular metacard, and is created at the same time as the metacard. +

[NOTE]
====
Attribute values can only be set/modified if the attribute exists in the metacard's metacard type.

Attributes are initially injected with blank values.
However, if an attempt is made to inject an attribute that already exists, the attribute will retain the original value.
====

See xref:metadatareference:catalog-taxonomy-intro.adoc[Catalog Taxonomy Definitions] for a list of attributes injected by default. +
See xref:developing:devcomponents/attribute-injection.adoc[Developing Attribute Injections] to learn how to configure attribute injections.
