:type: introduction
:status: published
:title: Documentation Guide
:section: Documentation Guide
:priority: 1
:order: 00

= Documentation Guide

The {branding} documentation is organized by audience.

xref:coreconcepts/core-concepts-intro.adoc[Core Concepts]::
This introduction section is intended to give a high-level overview of the concepts and capabilities of {branding}.

Administrators::
xref:managing:managing-intro.adoc[Managing] |
Administrators will be installing, maintaining, and supporting existing applications.
Use this section to xref:managing:installing/install-prereqs.adoc[prepare], xref:managing:installing/installing-intro.adoc[install], xref:managing:configuring/configuring-intro.adoc[configure], xref:managing:running/running-intro.adoc[run], and xref:managing:running/monitoring.adoc[monitor] {branding}.

Users::
xref:using:using-simple-search-ui.adoc[Using] |
Users interact with the system to search data stores.
Use this section to navigate the various user interfaces available in {branding}.

Integrators::
xref:integrating:integrating-intro.adoc[Integrating] |
Integrators will use the existing applications to support their external frameworks. This section will provide details for finding, accessing, and using the components of {branding}.

Developers::
xref:developing:devguidelines/contributing-intro.adoc[Developing] |
Developers will build or extend the functionality of the applications. 

== Documentation Conventions

The following conventions are used within this documentation:

=== Customizable Values

Many values used in descriptions are customizable and should be changed for specific use cases.
These values are denoted by `< >`, and by `[[ ]]` when within XML syntax. When using a real value, the placeholder characters should be omitted.

=== Code Values

Java objects, lines of code, or file properties are denoted with the `Monospace` font style.
Example: `ddf.catalog.CatalogFramework`

=== Hyperlinks

Some hyperlinks (e.g., `/admin`) within the documentation assume a locally running installation of {ddf-branding}. 
Simply change the hostname if accessing a remote host.

Hyperlinks that take the user away from the {branding} documentation are marked with an `external link` ({external-link}) icon.

== Support

Questions about {ddf-branding} should be posted to the https://groups.google.com/d/forum/ddf-users[ddf-users forum] {external-link} or https://groups.google.com/d/forum/ddf-developers[ddf-developers forum] {external-link}, where they will be responded to quickly by a member of the {ddf-branding} team.

===  Documentation Updates

The most current {ddf-branding} documentation is available at http://codice.org/ddf/Documentation-versions.html[{ddf-branding} Documentation] {external-link}.
