:title: Starting Intro
:type: startingIntro
:status: published
:summary: Starting and stopping an instance.
:order: 01

= Starting Intro

Follow the below steps to start and stop {branding}.

== Starting from Startup Scripts

Run one of the start scripts from a command shell to start the distribution and open a local console:

.Start Script: *NIX
[source,subs=attributes]
----
{home_directory}/bin/{branding-lowercase}
----

.Start Script: Windows
[source,subs=attributes]
----
{home_directory}/bin/{branding-lowercase}.bat
----

== Starting as a Background Process

Alternatively, to run {branding} as a background process, run the `start` script:

.*NIX
[source,subs=attributes]
----
{home_directory}/bin/start
----

.Windows
[source,subs=attributes]
----
{home_directory}/bin/start.bat
----

[NOTE]
====
If console access is needed while running as a service, run the `client` script on the host where the {branding} is running:

.*NIX
[source,subs=attributes]
----
{home_directory}/bin/client
----

.Windows
[source,subs=attributes]
----
{home_directory}/bin/client.bat -h <FQDN>
----

Use the `-h` option followed by the name (`<FQDN>`) or IP of the host where {branding} is running.
====

== Stopping {branding}

There are two options to stop a running instance:

* Call shutdown from the console:

.Shut down with a prompt
[source,subs=attributes]
----
{branding-lowercase}@local>shutdown
----

.Force Shutdown without prompt
[source,subs=attributes]
----
{branding-lowercase}@local>shutdown -f
----

* Keyboard shortcut for shutdown
** `Ctrl`-`D`
** `Cmd`-`D`
* Or run the stop script:

.*NIX
[source,subs=attributes]
----
{home_directory}/bin/stop
----

.Windows
[source,subs=attributes]
----
{home_directory}/bin/stop.bat
----

.Shut Down
[IMPORTANT]
====
Do not shut down by closing the window (Windows, Unix) or using the `kill -9 <pid>` command (Unix).
This prevents a clean shutdown and can cause significant problems when {branding} is restarted.
Always use the shutdown command or the shortcut from the command line console.
====
