:title: Security Hardening
:type: securing
:status: published
:summary: Introduction to Hardening.
:parent: Securing
:order: 00

= Security Hardening

.Security Hardening
****
To harden {branding}, extra security precautions are required.

Where available, necessary migitations to harden an installation of {branding} are called out in the following configuration steps.

Refer to the xref:managing:securing/hardening-checklist.adoc[Hardening Checklist] for a compilation of these mitigations.
****

[NOTE]
====
The  security precautions are best performed as configuration is taking place, so hardening steps are integrated into configuration steps.
====

This is to avoid setting an insecure configuration and having to revisit during hardening.
Most configurations have a security component to them, and important considerations for hardening are labeled as such during configuration as well as provided in a checklist format.

Some of the items on the checklist are performed during xref:installing/installing-intro.adoc[installation] and others during xref:configuring/configuring-intro.adoc[configuration].
Steps required for hardening are marked as *Required for Hardening* and are collected here for convenience.
Refer to the checklist during system setup.
