:title: Configuring
:type: managingSection
:status: published
:summary: Introduction to system configuration.
:order: 01

= Configuring

{branding} is highly configurable and many of the components of the system can be configured to use an included {branding} implementation or replaced with an existing component of an integrating system.

.Configuration Requirements
[NOTE]
====
Because components can easily be installed and uninstalled, it's important to remember that for proper {branding} functionality, at least the Catalog API, one Endpoint, and one Catalog Framework implementation must be active.
====

.Configuration Tools
{branding} provides several tools for configuring the system.
The xref:managing:configuring/admin-console-tutorial.adoc[{admin-console}] is a useful interface for configuring applications, their features, and important settings.
Alternatively, many configurations can be updated through xref:managing:configuring/console-commands-ref.adoc[console commands] entered into the {command-console}.
Finally, configurations are stored in xref:managing:configuring/configuration-files.adoc[configuration files] within the `{home_directory}` directory.

.Configuration Outline
While many configurations can be set or changed in any order, for ease of use of this documentation, similar subjects have been grouped together sequentially.

See xref:managing:installing/managing-certificates.adoc[Keystores and certificates] to set up the certificates needed for messaging integrity and authentication.
Set up xref:managing:configuring/configuring-user-access.adoc[Users] with security attributes, then configure xref:managing:configuring/configuring-data-management.adoc[data] attribute handling, and finally, define the xref:managing:configuring/configuring-security-policies[Security Policies] that map between users and data and make decisions about access.

Connecting {branding} to other data sources, including other instances of {branding} is covered in the xref:managing:configuring/configuring-federation.adoc[Configuring Federation] section.

Lastly, see the xref:managing:configuring/special-configurations.adoc[Configuring for Special Deployments] section for guidance on common specialized installations, such as xref:managing:configuring/configuring-fanout-proxy.adoc[fanout] or xref:managing:configuring/reusing-configurations.adoc[multiple identical configurations].
