:title: Configuring Data Policy Plugins
:type: configuration
:status: published
:summary: Configuring policy plugins
:parent: Configuring Data Management
:order: 05

= Configuring Data Policy Plugins

Configure the data-related policy plugins to determine the accessibility of data held by {branding}.

== Configuring the Metacard Attribute Security Policy Plugin

The Metacard Attribute Security Policy Plugin combines existing metacard attributes to make new attributes and adds them to the metacard.

. Navigate to the *{admin-console}*.
. Select the *{ddf-catalog}* application tile
. Select the *Configuration* tab
. Select the *Metacard Attribute Security Policy Plugin*.

Sample configuration of the xref:architectures:metacard-attribute-plugin.adoc[Metacard Attribute Security Policy Plugin].

To configure the plugin to combine the attributes `sourceattribute1` and `sourceattribute2` into a new
attribute `destinationattribute1` using the union,
enter these two lines under the title **Metacard Union Attributes**

|===
|Metacard Union Attributes

|`sourceattribute1=destinationattribute1`

|`sourceattribute2=destinationattribute1`
|===

include::reference:partial$MetacardAttributePlugin.adoc[]

== Configuring the Metacard Validation Marker Plugin

By default, the Metacard Validation Marker Plugin will mark metacards with validation errors and warnings as they are reported by each metacard validator and then allow the ingest.
To prevent the ingest of certain invalid metacards, the `Metacard Validity Marker` plugin can be configured to "enforce" one or more validators.
Metacards that are invalid according to an "enforced" validator will not be ingested.

. Navigate to the *{admin-console}*.
. Select the *{ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the *Metacard Validity Marker Plugin*.
.. If desired, enter the ID of any metacard validator to enforce. This will prevent ingest of metacards that fail validation.
.. If desired, check *Enforce Errors* or *Enforce Warnings*, or both.

include::reference:partial$MetacardValidityMarkerPlugin.adoc[]

== Configuring the Metacard Validity Filter Plugin

The xref:architectures:metacard-validity-filter.adoc[Metacard Validity Filter Plugin] determines whether metacards with validation errors or warnings are filtered from query results.

. Navigate to the *{admin-console}*.
. Select the *{ddf-catalog}* application.
. Select the *Configuration* tab.
. Select the *Metacard Validity Filter Plugin*.
.. Check *Filter Errors* to hide metacards with errors from users.
.. Check *Filter Warnings* to hide metacards with warnings from users.

include::reference:partial$MetacardValidityFilterPlugin.adoc[]

== Configuring the XML Attribute Security Policy Plugin

The XML Attribute Security Policy Plugin finds security attributes contained in a metacard's metadata.

. Navigate to the {admin-console}.
. Select the *{ddf-catalog}* application tile.
. Select the *Configuration* tab.
. Select the *XML Attribute Security Policy Plugin* configuration.

include::reference:partial$XmlAttributePlugin.adoc[XML Attribute Security Policy Plugin
 configurations] for all possible configurations.

