:title: Feature Commands
:type: configuration
:status: published
:parent: Console Command Reference
:order: 02
:summary: Managing features from the {command-console}.

= Feature Commands

Individual features can also be added via the {command-console}.

. Determine which feature to install by viewing the available features on {branding}. +
`{branding-lowercase}@local>feature:list`
. The console outputs a list of all features available (installed and uninstalled). A snippet of the list output is shown below (the versions may differ):

[subs="verbatim,attributes"]
----
State         Version            Name                                     Repository                           Description
[installed  ] [{ddf-version}  ] security-handler-api                     security-services-app-{ddf-version} API for authentication handlers for web applications.
[installed  ] [{ddf-version}  ] security-core                            security-services-app-{ddf-version} DDF Security Core
[uninstalled] [{ddf-version}  ] security-expansion                       security-services-app-{ddf-version} DDF Security Expansion
[installed  ] [{ddf-version}  ] security-pdp-authz                       security-services-app-{ddf-version} DDF Security PDP.
[uninstalled] [{ddf-version}  ] security-pep-serviceauthz                security-services-app-{ddf-version} DDF Security PEP Service AuthZ
[uninstalled] [{ddf-version}  ] security-expansion-user-attributes       security-services-app-{ddf-version} DDF Security Expansion User Attributes Expansion
[uninstalled] [{ddf-version}  ] security-expansion-metacard-attributes   security-services-app-{ddf-version} DDF Security Expansion Metacard Attributes Expansion
[installed  ] [{ddf-version}  ] security-sts-server                      security-services-app-{ddf-version} DDF Security STS.
[installed  ] [{ddf-version}  ] security-sts-realm                       security-services-app-{ddf-version} DDF Security STS Realm.
[uninstalled] [{ddf-version}  ] security-sts-ldaplogin                   security-services-app-{ddf-version} DDF Security STS JAAS LDAP Login.
[uninstalled] [{ddf-version}  ] security-sts-ldapclaimshandler           security-services-app-{ddf-version} Retrieves claims attributes from an LDAP store.
----
. Check the bundle status to verify the service is started. +
`{branding-lowercase}@local>list`

The console output should show an entry similar to the following:
[subs="verbatim,attributes"]
----
[ 117] [Active     ] [            ] [Started] [   75] {ddf-branding} :: Catalog :: Source :: Dummy (<version>)
----

== Uninstalling Features from the {command-console}

. Check the feature list to verify the feature is installed properly. +
`{branding-lowercase}@local>feature:list`

[subs="verbatim,attributes"]
----
State         Version          Name                          Repository  		   Description
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-core                      {ddf-branding-lowercase}-{ddf-version}
[uninstalled] [{ddf-version}         ] {ddf-branding-lowercase}-sts                       {ddf-branding-lowercase}-{ddf-version}
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-security-common           {ddf-branding-lowercase}-{ddf-version}
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-resource-impl             {ddf-branding-lowercase}-{ddf-version}
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-source-dummy              {ddf-branding-lowercase}-{ddf-version}
----

. Uninstall the feature. +
`{branding-lowercase}@local>feature:uninstall {branding-lowercase}-source-dummy`

[WARNING]
====
Dependencies that were auto-installed by the feature are not automatically uninstalled.
====

. Verify that the feature has uninstalled properly. +
`{branding-lowercase}@local>feature:list`

[subs="verbatim,attributes"]
----
State         Version          Name                          Repository  Description
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-core                      {ddf-branding-lowercase}-{ddf-version}
[uninstalled] [{ddf-version}         ] {ddf-branding-lowercase}-sts                       {ddf-branding-lowercase}-{ddf-version}
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-security-common           {ddf-branding-lowercase}-{ddf-version}
[installed  ] [{ddf-version}         ] {ddf-branding-lowercase}-resource-impl             {ddf-branding-lowercase}-{ddf-version}
[uninstalled] [{ddf-version}         ] {ddf-branding-lowercase}-source-dummy              {ddf-branding-lowercase}-{ddf-version}
----
