:title: Eventing
:type: architectureIntro
:status: published
:children:
:order: 07
:summary: Introduction to Pub/Sub.

= Eventing


The Eventing capability of the Catalog allows endpoints (and thus external users) to create a "standing query" and be notified when a matching metacard is created, updated, or deleted.

Notably, the Catalog allows event evaluation on both the previous value (if available) and new value of a Metacard when an update occurs.

Eventing allows {branding}s to receive events on operations (such as create, update, delete) based on particular queries or actions.
Once subscribed, users will receive notifications of events such as update or create on any source.

== Eventing Components

The key components of {branding} Eventing include:

* xref:developing:devcomponents/subscriptions.adoc#developing_subscriptions[Subscription]
* xref:developing:devcomponents/subscriptions.adoc#delivery_method[Delivery Method]
* xref:architectures:event-processor.adoc[Event Processor]


