:type: plugin
:status: published
:title: Metacard Validity Marker
:link: _metacard_validity_marker
:plugintypes: preingest
:summary: Modifies metacards when created or ingested according to metacard validator services.

= Metacard Validity Marker

The Metacard Validity Marker Pre-Ingest plugin modifies the metacards contained in create and update requests.

The plugin runs each metacard in the `CreateRequest` and `UpdateRequest` against each registered `MetacardValidator` service.

[NOTE]
====
This plugin can make it seem like ingested resources are not successfully ingested if a user does not have permissions to access invalid metacards.
If an ingest did not fail, there are no errors in the ingest log, but the expected results do not show up after a query,
verify either that the ingested data is valid or that the xref:architectures:/metacard-validity-filter.adoc[Metacard Validity Filter Plugin] is configured to show warnings and/or errors.
====

== Installing Metacard Validity Marker

This plugin is installed by default with a standard installation in the {ddf-catalog} application.

== Configuring Metacard Validity Marker

include::reference:partial$MetacardValidityMarkerPlugin.adoc[]

== Using Metacard Validity Marker

Use this pre-ingest plugin to validate metacards against metacard validators, which can check schemas, schematron, or any other logic. 
