:title: High Availability Initial Setup
:type: installing
:status: published
:summary: Initial setup in a Highly Available Cluster.
:project: {branding}
:order: 10

= High Availability Initial Setup

This section describes how to complete the initial setup of {branding} in a xref:introduction:coreconcepts/high-availability-intro.adoc[Highly Available Cluster].

.Prerequisites
* A failover proxy that can route HTTP traffic according to the pattern described in the Introduction to High Availability.
It is recommended that a hardware failover proxy be used in a production environment.
* SolrCloud: See the xref:managing:configuring/sources/solr-catalog-provider.adoc[SolrCloud section] for installation and configuration
guidance to connect {branding} nodes to SolrCloud.

Once the prerequisites have been met, the below steps can be followed.

[NOTE]
====
Unless listed in the xref:managing:high_availability_initial_setup_exceptions,High Availability Initial Setup Exceptions>> section,
the normal steps can be followed for installing, configuring, and hardening.
====

. Install the first {branding} node. See the xref:managing:installing/installing-intro.adoc[Installation Section].
. Configure the first {branding} node. See the xref:managing:configuring/configuring-intro.adoc[Configuring Section].
. Optional: If hardening the first {branding} node (excluding setting directory permissions). See the xref:managing:securing/hardening-intro.adoc[Hardening Section].
. Export the first {branding} node's configurations, install the second {branding} node, and import the exported configurations on that node.
See xref:managing:configuring/reusing-configurations.adoc[Reusing Configurations].
. If hardening, set directory permissions on both {branding} nodes. See xref:managing:installing/file-system-access.adoc#setting_directory_permissions[Setting Directory Permissions].
